Completed node-fs-readfile
CTMendoza/mod2-0822-code-solutions pull request #20
Opened 2022-10-05 04:14 UTC by CTMendoza

![node-fs-readfile](https://user-images.githubusercontent.com/90743100/193979287-db8fa294-b2ed-4f0f-8b0f-a1bb6b1fc0e6.gif)

2022-10-05 04:27 UTC, TimelikeClosure requested changes

2022-10-05 04:27 UTC, TimelikeClosure commented on node-fs-readfile/read-any.js
> +}
This should work for any filename, not just the starter files.

2022-10-05 16:37 UTC, CTMendoza commented
![node-fs-readfile update](https://user-images.githubusercontent.com/90743100/194114390-5b339c05-e098-46b1-b123-016f3e9cb969.png)

Updated screenshot. Code functionality now allows to read any file in the directory including .js files.

2022-10-07 01:24 UTC, TimelikeClosure approved these changes

2022-10-11 01:41 UTC, merged